# Generated by Django 4.2.5 on 2023-09-15 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(default='', max_length=200)),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(default='', max_length=200)),
                ('worker_birthday', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Workers',
            },
        ),
    ]
